version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: amee_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes: 
     - ./data:/var/lib/potgresql/data
    ports:
     - 5432:5432
  

     

  